print('int:', 10)
print('float:', 1.0)
print(type(1e3))
print('complex:', 1 + 2j)
print('bool:', True)
print(type(True))
print('str:', 'Hello')
print('NoneType:', None)
print(type(None))
print('list:', [1, 2, 3])
print(type([1, 2, 3]))
print('tuple:', (1, 2, 3))
print('set:', {1, 2, 3})
print('dict:', {'a': 1, 'b': 2, 'c': 3})